spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SagarSisodiya/service-configuration-dev.git
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
server:
  port: 8071
